apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-data
spec:
  template:
    spec:
      containers:
        - name: player-data-service
          image: ghcr.io/malikbenkirane/oha-opus-major:67be46060074a379c7c974641e7e99f254d2d041
