apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: demo-

resources:
- ../../base

labels:
- includeSelectors: true
  pairs:
    variant: demo

patches:
- path: deployment.yaml
